-- SQL Retail Data Analysis

CREATE DATABASE Retail_Data_Analysis
use Retail_Data_Analysis


-- DATA PREPARATION AND UNDERSTANDING

--1. What is the total number of rows in each of the 3 tables in the database? 
--Q1--BEGIN
	
	select 'Customer' [No Of Records], COUNT(*) from Customer UNION all
	select 'Product_Category' [No Of Records], COUNT(*) from Product_Category UNION all
	select 'Transactions' [No Of Records], COUNT(*) from Transactions

--Q1--END


--2. What is the total number of transactions that have a return?
--Q2--BEGIN
	
	select COUNT(Qty) from Transactions
	where Qty > 0
	
--Q2--END


--3. Convert the date variables into valid date formats 
--Q3--BEGIN
	
	--Date formatting is done while importing the data.

--Q3--END


--4. What is the time range of the transaction data available for analysis? 
--Q4--BEGIN

	SELECT
	DATEDIFF(day, MIN(tran_date), MAX(tran_date)) AS Days,
	DATEDIFF(month, MIN(tran_date), MAX(tran_date)) AS Months,
	DATEDIFF(year, MIN(tran_date), MAX(tran_date)) AS Years
	FROM Transactions;

--Q4--END

--5. Which product category does the sub-category “DIY” belong to? 
--Q5--BEGIN

	select distinct(prod_cat) from Product_Category
	where prod_subcat = 'DIY'

--Q5--END
	

-- Data Analysis --

--1. Which channel is most frequently used for transactions? --Q1--BEGIN

	select top 1 Store_type , COUNT(transaction_id)[No of Transaction] from Transactions
	group by Store_type
	order by COUNT(transaction_id) desc

--Q1--END

--2. What is the count of Male and Female customers in the database? --Q2--BEGIN

	SELECT Gender, COUNT(*) as CustomerCount
	FROM Customer
	GROUP BY Gender;

--Q2--END

--3. From which city do we have the maximum number of customers and how many? --Q3--BEGIN

	Select top 1 city_code, count(customer_id) as customercount from Customer
	group by city_code
	order by count(customer_id) desc

--Q3--END

--4. How many sub-categories are there under the Books category? --Q4--BEGIN

	select prod_cat, COUNT(prod_subcat)[No of sub-categories] from Product_Category
	where prod_cat = 'Books'
	group by prod_cat

--Q4--END

--5. What is the maximum quantity of products ever ordered? 
--Q5--BEGIN

	select MAX(Qty)[maximum quantity of products ordered] from Transactions

--Q5--END

--6. What is the net total revenue generated in categories Electronics and Books? 
--Q6--BEGIN

	select prod_cat, sum(total_amt) as Net_total_rev from Transactions as T1
	inner join Product_Category as T2 on T1.prod_cat_code = T2.prod_cat_code and
	T1.prod_subcat_code = T2.prod_sub_cat_code
	where prod_cat in ('Electronics' , 'Books')
	group by prod_cat

--Q6--END

--7. How many customers have >10 transactions with us, excluding returns? --Q7--BEGIN

	Select cust_id, count(transaction_id) as no_of_transactions from Transactions
	where total_amt > 0
	group by cust_id
	having count(transaction_id) > 10

--Q7--END

--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”? 
--Q8--BEGIN

	Select prod_cat, T2.store_type, sum(T2.total_amt) as Combind_revenue from Product_Category as T1
	inner join Transactions T2
	on T1.prod_cat_code =T2.prod_cat_code 
	and T1.prod_sub_cat_code = T2.prod_subcat_code
	where prod_cat in ('Electronics' , 'clothing')
	and Store_type = 'Flagship store'
	group by prod_cat, T2.Store_type

--Q8--END

--9. What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat. 
--Q9--BEGIN

	Select prod_subcat, sum(T2.total_amt) as total_revenue from Product_Category as T1
	left join Transactions as T2
	on T1.prod_cat_code = T2.prod_cat_code
	and T1.prod_sub_cat_code = T2.prod_subcat_code
	left join Customer as T3
	on T3.customer_Id = T2.cust_id
	where Gender = 'M' and prod_cat = 'Electronics'
	group by prod_subcat

--Q9--END

--10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales? 
--Q10--BEGIN

	Select top 5 prod_subcat,
	(Sum(case when total_amt > 0  Then total_amt  end)/SUM(total_amt))*100 as Sales_percentage,
	abs (Sum( Case when total_amt < 0 THEN total_amt  end)/Sum(total_amt))*100 as  Return_percentage
	From Product_Category inner join Transactions 
	on Product_Category.prod_sub_cat_code =Transactions.prod_subcat_code
	and Product_Category.prod_cat_code=Transactions.prod_cat_code
	group by prod_subcat
	order by Sales_percentage desc

--Q10--END

/*11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these consumers in last 30 days of transactions from max transaction
date available in the data? */
--Q11--BEGIN

	Select sum(total_amt) as total_sales from Customer as T1 inner join Transactions as T2
	on T1.customer_Id = T2.cust_id
	where DOB between DATEADD(year, -35,(select max(tran_date) from Transactions)) 
	and DATEADD(year, -25,(select max(tran_date) from Transactions)) and
	tran_date >= (select dateadd(day, -30, max(tran_date)) from Transactions)

--Q11--END

--12.Which product category has seen the max value of returns in the last 3 months of transactions?
--Q12--BEGIN

	select prod_cat, sum(total_amt) as total_sum from Product_Category as T1
	inner join Transactions as T2 on T1.prod_cat_code = T2.prod_cat_code and
	T1.prod_sub_cat_code = T2.prod_subcat_code
	where total_amt < 0 and tran_date between DATEADD(month, -3, (select max(tran_date) from transactions))
	and (select max(tran_date) from transactions)
	group by prod_cat
	order by total_sum desc

--Q12--END

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?
--Q13--BEGIN

	select Store_type from (select t2.[Store_type], sum(t2.[total_amt]) [ttl_sales], sum(t2.[Qty]) [ttl_qty] 
				from [dbo].[Product_Category] t1 , [dbo].[Transactions] t2 
				where t1.[prod_cat_code] = t2.[prod_cat_code] 
				and t1.[prod_sub_cat_code] = t2.[prod_subcat_code] 
				and t2.[total_amt] > 0 and t2.[Qty] > 0
				group by t2.[Store_type]) y , (select max(x.ttl_amt) TAmt, max(x.ttl_qty) TQty
 										from (select t2.[Store_type], sum(t2.[total_amt]) ttl_amt, sum(t2.[Qty]) [ttl_qty] 
											from [dbo].[Product_Category] t1 , [dbo].[Transactions] t2 
											where t1.[prod_cat_code] = t2.[prod_cat_code] 
											and t1.[prod_sub_cat_code] = t2.[prod_subcat_code] 
											and t2.[total_amt] > 0 and t2.[Qty] > 0
											group by t2.[Store_type]) x)z
where y.ttl_sales =  z.TAmt and y.ttl_qty = z.TQty

--Q13--END

--14.What are the categories for which average revenue is above the overall average. 
--Q14--BEGIN

	Select prod_cat, avg(total_amt) as average_Revenue
	from Transactions as T1
	inner join Product_Category as T2
	on T1.prod_cat_code = T2.prod_cat_code
	and T1.prod_subcat_code = T2.prod_sub_cat_code
	group by prod_cat
	having avg(total_amt) > (select AVG(total_amt) from dbo.Transactions)

--Q14--END

--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold. 
--Q15--BEGIN

	select prod_cat, prod_subcat, avg(total_amt) as Avg_revenue, sum(total_amt) as total_revenue 
	from Transactions as T1 inner join Product_Category as T2
	on T1.prod_cat_code = T2.prod_cat_code and T1.prod_subcat_code = T2.prod_sub_cat_code
	where prod_cat in
	(select top 5 prod_cat from Transactions inner join Product_Category on T1.prod_cat_code = T2.prod_cat_code 
	group by prod_cat
	order by sum(qty) desc)
	group by prod_cat, prod_subcat

--Q15--END